# Generated by Django 3.0.3 on 2020-03-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='created',
            field=models.DateField(default='2020-03-01'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateField(default='2020-03-01'),
        ),
    ]
