# Generated by Django 3.0.3 on 2020-03-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20200303_1146'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('due_time', models.TimeField()),
            ],
        ),
    ]
