# Generated by Django 3.0.3 on 2020-03-04 10:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20200304_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2020, 3, 4, 10, 53, 11, 570634, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateField(default='2020-03-04'),
        ),
    ]
