# Generated by Django 3.0.3 on 2020-05-12 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20200511_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingitem',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2020, 5, 12, 10, 4, 43, 675620, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateField(default='2020-05-12'),
        ),
    ]
