# Generated by Django 3.0.3 on 2020-05-16 12:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20200512_1647'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.AlterField(
            model_name='meetingitem',
            name='due_time',
            field=models.TimeField(default=datetime.datetime(2020, 5, 16, 12, 33, 39, 979202, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created',
            field=models.DateField(default='2020-05-16'),
        ),
    ]
